---
# Ansible role for creating a site on Site Factory
# https://github.com/SU-SWS/drupal-caravan
# ================================================
#
# The purpose of this role is to instantiate a STATE, in this case the state of
# a host 
#
# INPUTS:
#   sitename
#   profile
#   stack
#   stack_id
#   localhost_home
#   acquia_username
#   acquia_api_key
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Check if site exists on Site Factory
  uri:
    url: https://www.stanford.acsitefactory.com/api/v1/sites
    method: GET
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    force_basic_auth: yes
    body_format: json
    return_content: yes
  register: existing_sites

- name: Display all site names
  debug: var=item
  with_items: "{{ existing_sites | json_query('json.sites[*].site') }}"

- name: Create new site on Site Factory
  uri:
    url: https://www.stanford.acsitefactory.com/api/v1/sites
    method: POST
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    body:
      site_name: "{{ sitename }}"
      install_profile: "{{ profile }}"
      codebase: "{{ stack_id }}"
      group_ids: 126
    force_basic_auth: yes
    body_format: json
    return_content: yes
  register: site_created
  when: sitename not in existing_sites | json_query('json.sites[*].site')

- name: Display ACSF site id
  debug:
    msg: "{{ site_created | json_query('json.id') }}"

- pause: minutes=6
  when: sitename not in existing_sites | json_query('json.sites[*].site')
# - name: Check task
