---
# Ansible role for creating a site on Site Factory
# https://github.com/SU-SWS/drupal-caravan
# ================================================
#
# The purpose of this role is to instantiate a STATE, in this case the state of
# a host 
#
# INPUTS:
#   sitename
#   profile
#   stack
#   stack_id
#   localhost_home
#   acquia_username
#   acquia_api_key
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Check if site exists on Site Factory
  uri:
    url: https://www.stanford.acsitefactory.com/api/v1/sites
    method: GET
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    body: "{{ lookup('file','issue.json') }}"
    force_basic_auth: yes
    status_code: 201
    body_format: json
    return_content: yes
  register: exising_site

- name: Create new site on Site Factory
  uri:
    url: https://www.stanford.acsitefactory.com/api/v1/sites
    method: POST
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    body: "{{ lookup('file','issue.json') }}"
      site_name: "{{ sitename }}"
      install_profile: "{{ profile }}"
      codebase: "{{ stack_id }}"
      group_ids: 126
    force_basic_auth: yes
    status_code: 201
    body_format: json
    return_content: yes
  register: site_created
  when: existing_site == ""

- pause: minutes=5

- name: Poll ACSF until site is complete, then move on
  command: "drush sa @{{ stack }}.01live.{{ sitename }} vget site_name"
  register: installed_sitename
  until: installed_sitename == "{{ sitename }}"
  retries: 30
  delay: 10
