---
# Ansible role for creating a site on Site Factory
# https://github.com/SU-SWS/drupal-caravan
# ================================================
#
# This should be run on host
# We'll need an inventory of sites.stanford.edu domains
# And an inventory of new sitefactory names.
#
# The purpose of this role is to instantiate a STATE, in this case the state of
# a host 
#
# INPUTS:
#   sitename
#   container_distro
#   container_ip_address
#   localhost_http_port
#   localhost_https_port
#   localhost_project_path
#   container_webserver_root
#   localhost_home_path
#   localhost_ssh_key_name
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# Docker is running on host machine.
#
# KNOWN ISSUES:
# https://github.com/ansible/ansible/issues/20492

- name: Create new site on Site Factory
  uri:
    url: https://www.stanford.acsitefactory.com/api/v1/sites
    method: POST
    user: your_username // not email
    password: your_pass // api_key
    body: "{{ lookup('file','issue.json') }}"
      site_name: "{{ sitename }}"
      install_profile: "standard"
      codebase: 2
      group_ids: 126
    force_basic_auth: yes
    status_code: 201
    body_format: json

- name: Poll ACSF until site is complete, then move on
  status
wait_for:
ping occassionally

- name: Get params for drush aliases
  

- name: Update drush aliases
  template:
    src: "cardinal.aliases.drushrc.php"
    dest: "{{ container_webserver_root }}{{ sitename }}/drush/site-aliases/cardinal.aliases.drushrc.php"


- name: Refresh Ansible inventory
  meta: refresh_inventory
