---
# Ansible role for syncing the database and files between Sites and Site Factory.
# https://github.com/SU-SWS/drupal-caravan
# =====================================================================
#
# This role syncs the database from Sites to Site Factory. To do this,
# it will first save a copy locally and then rsync the local copy to
# Site Factory.
#
# INPUTS:
#   sitename
#   server_alias
#   site_prefix
#   stack
#   server
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Download copy of database from sites
  shell: "drush @{{ server_alias }}.{{ site_prefix }}_{{ sitename }} sql-dump > /tmp/{{ sitename }}/dbdump.sql"

- name: Drop database in Site Factory and install new database
  shell: "drush @acsf.{{ stack }}.{{ sitename }} {{ item }}"
  with_items:
    - "-y sql-drop"
    - "sqlc < /tmp/{{ sitename }}/dbdump.sql"
    - "-y en acsf"
    - "-y dis webauth"
    - "-y updb"
#    - "rr"

- name: Copy files from Sites to local
  shell: "rsync -avz {{ sunetid }}@{{ server }}.stanford.edu:/afs/ir/dist/drupal/{{ site_prefix }}_{{ sitename }}/files/* /tmp/{{ sitename }}/files/."

- name: Copy files from local to Site Factory
  shell: "drush -y rsync /tmp/{{ sitename }}/files/ @acsf.{{ stack }}.{{ sitename }}:%files/"
