---
# Ansible role that setups up drush aliases for @self and container
# https://github.com/SU-SWS/drupal-caravan
# ================================================================
#
# The purpose of this role is to instantiate a STATE, in this case the state of
# drush aliases for accessing the site we've just created.
#
# INPUTS:
#   sitename
#   container_webserver_root
#   container_production_host_address
#   container_php_version
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# Acquia BLT in vendor directory.
#
# KNOWN ISSUES:
# --
#

- name: Copy local site alias
  template:
    src: "caravan.aliases.drushrc.php.yml.j2"
    dest: "{{ container_webserver_root }}{{ sitename }}/drush/site-aliases/caravan.alises.drushrc.php"

- name: Fix local site url for alias
  template:
    src: "local.drushrc.php.j2"
    dest: "{{ container_webserver_root }}{{ sitename }}/docroot/sites/default/local.drushrc.php"

- name: Test alias
  command: "drush @{{ sitename }}.local uli"
