---
# https://github.com/ansible/ansible/issues/20492
# Currently requires Python3
- name: Create a container
  docker_container:
    name: "{{ drupal_domain }}"
    image: "geerlingguy/docker-{{ distro }}-ansible:latest"
    ports:
      - "{{ drupalvm_ip_address }}:{{ drupalvm_http_port }}:80"
      - "{{ drupalvm_ip_address }}:{{ drupalvm_https_port }}:433"
    volumes:
      - "{{ local_project_root }}:{{ drupalvm_project_root }}/:{{ volume_opts }}"
    state: started
    restart: yes
    privileged: yes
    command: /lib/systemd/systemd
