---
# Ansible role for removing changes made to localhost
# https://github.com/SU-SWS/drupal-caravan
# ===================================================
#
# The purpose of this role is to run TASKS, in this case remove an entry
# from /etc/hosts, remove an IP alias, stop and remove a Docker container.
#
# INPUTS:
#   sitename
#   ip_address
#   ansible_os_family
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# Permission to edit /etc/hosts
#
# KNOWN ISSUES:
# I have copied the setup-localhost handlers directory.  I should be able to
# use their handler, without having the duplicate the directory.

- name: Remove container IP to /etc/hosts
  lineinfile:
    path: /etc/hosts
    insertafter: EOF
    line: "{{ container_ip_address }}  {{ item }}.local"
    state: absent
  become: true
  with_items:
    - "{{ sitename }}"
    - "behat.{{ sitename }}"

- name: Remove IP alias
  command: "ifconfig lo0 -alias {{ container_ip_address }}"
  become: true
  when: ansible_os_family == "Darwin"
  ignore_errors: yes

- name: Remove Docker container
  docker_container:
    name: "{{ sitename }}"
    state: absent

- name: Remove Docker image
  docker_image:
    name: "geerlingguy/docker-{{ container_distro }}-ansible:latest"
    state: absent

- name: Remove pip packages
  pip:
    name:
      - docker-py
      - docker-pycreds
    state: absent
