---
# Ansible role that uses BLT to run Behat tests
# https://github.com/SU-SWS/drupal-caravan
# =======================================================
#
# The purpose of this role is to run a TASK, in this case an Acquia BLT
# process that runs all Behat tests in the build repo's tests directory.
#
# INPUTS:
#   sitename
#   container_webserver_root
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# Acquia BLT in vendor directory.
#
# KNOWN ISSUES:
# - We want BLT to find all Behat tests throughout the build repo.
#

- name: run Behat tests with BLT
  shell:
    cmd: vendor/bin/blt sws:behat
    chdir: "{{ container_webserver_root }}{{ sitename }}"
  async: 45
  poll: 5
