# Docker container information
docker_container_name: "{{ drupal_domain }}"
docker_image_name: "{{ drupal_domain }}"
docker_image_path: .

# Variables required by setup-container.yml
sitename: "se3_blt"
drupal_domain: "se3_blt"
distro: "ubuntu1604"
drupalvm_ip_address: "192.168.88.88"
drupalvm_http_port: "9000"
drupalvm_https_port: "9001"
drupalvm_ssh_port: "22"
ssh_key_name: "acquia_id_rsa"
drupalvm_project_root: "/var/www/se3_blt"
drupal_vhost_path: "/var/www/se3_blt/docroot"
home: "/Users/kelliebrownell"
drupalvm_machine_name: "{{ drupal_domain }}"
local_project_root: "/Users/jgknox/Sites/stanford-acquia/se3_blt"
drupalvm_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"

# Attempting to override DrupalVM default variables
drupal_db_user: "{{ drupal_domain }}"
drupal_db_password: "{{ drupal_domain }}"
drupal_db_name: "{{ drupal_domain }}"

apache_vhost_php_fpm_parameters: |
    <FilesMatch \.php$>
      SetHandler "proxy:fcgi://{{ php_fpm_listen }}"
    </FilesMatch>

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_vhost_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

mysql_databases:
  - name: "{{ drupal_domain }}"
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: "{{ drupal_domain }}"
    host: "%"
    password: "{{ drupal_domain }}"
    prov: "{{ drupal_domain }}.*:ALL"

# This comes from an if statement in DrupalVM's bake.sh script
# The value should be 'rw,cached' if OSTYPE=="darwin"*
# otherwise, it should be 'rw'.
volume_opts: "rw,cached"

# Path information
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"
ssh_home: /var/www/"{{ sitename }}"

# DrupalVM override: do not install a vanilla Drupal site
drupal_build_composer_project: false
drupal_build_composer: false
drupal_composer_path: false
drupal_install_site: false

# DrupalVM override: we need a drush alias in site-aliases
# I think; this installs an alias in /root/.drush
# But it would be nice if blt could find the alias in /root/.drush
# So that we wouldn't have to touch the build repo
configure_drush_aliases: true

installed_extras:
  - drush
  - selenium
  - vim

# Use PHP 5.6.
php_version: "5.6"
php_memory_limit: "1024M"

# Set selenium version and do not install Chrome yet
selenium_install_chrome: no
selenium_version: 2.47.1
