---
- include: "../../../geerlingguy/drupal-vm/tests/test-setup.yml"
- include: "../../../geerlingguy/drupal-vm/provisioning/playbook.yml"

- hosts: se3_blt
  connection: docker
  gather_facts: no
  become: yes
  user: root

  vars_files:
    - ../personal_vars.yml
    - vars.yml

  roles:
    - setup-acquia
    - install-site
