---
- hosts: 127.0.0.1
  connection: local
  become: yes

  vars_files:
    - ../personal_vars.yml

  roles:
    - setup-localhost
    - setup-container

  handlers:
    - name: restart Apache
      service: name=apache2 state=restarted
