---
# I'm using this to run docker.py
# Otherwise, it wasn't running and failing
- hosts: all
  tasks:
    - debug: msg="Host - {{ inventory_hostname }}"

- hosts: 127.0.0.1

  vars_files:
    - ../../../../caravan.yml

  roles:
    - setup-localhost
    - setup-container

  handlers:
    - name: restart Apache
      command: brew services restart httpd22

- hosts: se3_blt
  connection: docker
  gather_facts: no
  become: yes
  user: root

  vars_files:
    - ../../../../caravan.yml

  roles:
    - run-drupalvm

# Have not yet found a great way to inject a vars file
# Copying vars file to geerlingguy/drupal-vm/config.yml
- include: ../../../geerlingguy/drupal-vm/tests/test-setup.yml hosts="{{ sitename }}"
- include: ../../../geerlingguy/drupal-vm/provisioning/playbook.yml hosts="{{ sitename }}"

# I'd love to set this as a variable, but then why, one might ask
# use docker.py?  I assume it includes useful extra_vars related
# to communicating with this host.
- hosts: se3_blt
  connection: docker
  gather_facts: no
  become: yes
  user: root

  vars_files:
    - ../../../../caravan.yml

  roles:
    - setup-acquia
    - install-site
