---
# Ansible playbook that setups up a test environment and site copy.
# https://github.com/SU-SWS/drupal-caravan
# =================================================================
#
# This playbook contains five different sub-playbooks. They're broken out
# like this, so that I could include the DrupalVM playbooks without also having
# the ability to specify a variables file for DrupalVM's own Ansible playbooks.
#
# KNOWN ISSUES:
#   - The dynamic inventory docker.py was not running until after a failed
#     play run. I have added the first section, which simply prints a debug
#     statement, to kick off this docker.py script.
#   - Right now, I am limiting container playbooks with the string, "se3_blt".
#     Eventually, I need to turn this into a variable.
#   - docker.py includes as if it's a host, "unix://var/run/docker.sock".
#     See: https://groups.google.com/forum/#!topic/ansible-devel/QSWs-Jvks5c
#   - I had a handler for Play 2 to restart apache with brew. I have removed
#     that because Jeff recommended bundling handlers with roles. And demoed
#     a way to restart apache that is OS agnostic.
#   - Right now, I'm storing variables required by these roles in group_vars.
#     On the one hand, that allows us to be very specific about what those
#     values should be on different servers. On the other, it means that roles
#     are not technically self-sufficient.
#   - Install site comes last because that process blows away drupal-caravan.
#
# PLAY 2: Setup localhost and create container
# ============================================
- hosts: 127.0.0.1
  connection: local

  vars_files:
    - ../../../../caravan.yml

  roles:
    - setup-localhost
    - setup-container

# PLAY 3: Configure container
# ===========================
- hosts: "{{ sitename }}"
  connection: docker
  gather_facts: no
  become: yes
  user: root

  vars_files:
    - ../../../../caravan.yml

  roles:
    - setup-drupalvm


# PLAY 4: Run DrupalVM Ansible playbooks
# ========================================
- include: ../../../geerlingguy/drupal-vm/tests/test-setup.yml hosts="{{ sitename }}"
- include: ../../../geerlingguy/drupal-vm/provisioning/playbook.yml hosts="{{ sitename }}"


# PLAY 5: Setup Acquia and install site
# =======================================
- hosts: "{{ sitename }}"
  connection: docker
  gather_facts: no
  become: yes
  user: root

  vars_files:
    - ../../../../caravan.yml

  roles:
    - setup-acquia
    - setup-drush
    - setup-behat
    - install-site
