---
# Ansible role for setting up localhost to accomodate migration.
# https://github.com/SU-SWS/drupal-caravan
# =============================================================
#
# The purpose of this role is to instantiate a STATE, in this case the state of
# a directory on locahost, where we can temporarily sync a site database and files.
#
# INPUTS:
# sitename
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --
#
- name: Create sitename directory in tmp
  file:
    path: "/tmp/{{ sitename }}"
    state: absent
