# Docker container information
docker_container_name: "{{ drupal_domain }}"
docker_image_name: "{{ drupal_domain }}"
docker_image_path: .

# Variables required by setup-container.yml
sitename: "se3_blt"
drupal_domain: "se3_blt"
distro: "ubuntu1604"
drupalvm_ip_address: "192.168.88.88"
drupalvm_http_port: "9000"
drupalvm_https_port: "9001"
drupalvm_ssh_port: "22"
ssh_key_name: "acquia_id_rsa"
drupalvm_project_root: "/var/www/se3_blt"
drupal_vhost_path: "/var/www/se3_blt/docroot"
home: "/Users/kelliebrownell"
drupalvm_machine_name: "{{ drupal_domain }}"
local_project_root: "/Users/kelliebrownell/Sites/se3_blt"
drupalvm_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"

# This comes from an if statement in DrupalVM's bake.sh script
# The value should be 'rw,cached' if OSTYPE=="darwin"*
# otherwise, it should be 'rw'.
volume_opts: "rw,cached"
