---
# Ansible role that uses BLT to refresh or install a site
# https://github.com/SU-SWS/drupal-caravan
# =======================================================
#
# The purpose of this role is to run a TASK, in this case an Acquia BLT
# process that downloads a fresh copy of the site's production database
# and files.
#
# INPUTS:
#   sitename
#   container_webserver_root
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# Acquia BLT in vendor directory.
#
# KNOWN ISSUES:
# - BLT seems to believe this is a "staging" site. The masthead should say "local".
#   Shea suggests: When you get the `staging` title that means that the config import failed,
#   but the db import succeeded. That could be indicative of an error in the config and not the process.
# - BLT currently has a bug, that is not allowing sync:refresh to run without user input
#   https://github.com/acquia/blt/issues/1852
#   https://github.com/acquia/blt/pull/1862

#- name: install site with BLT
#  shell:
#    cmd: vendor/bin/blt sync:refresh -Dsync.files=true -n -y
#    chdir: "{{ container_webserver_root }}{{ sitename }}"

- name: Run BLT drush commands
  shell:
    cmd: vendor/bin/drush "{{ item }}"
    chdir: "{{ container_webserver_root }}{{ sitename }}"
  with_items:
    - cache-clear drush --uri=default --yes
    - sql-sync @earth.test @self --structure-tables-key=lightweight --create -db --sanitize --uri=default -yes
    - cache-clear drush --uri=default --yes
    - rsync '@earth.test:%files' /var/www/{{ sitename }}/docroot/sites/default/files --exclude-paths='styles:css:js' -yes
    - cc drush --uri=default --yes
    - cache-rebuild --uri=default --yes
    - updb --uri=default --yes
    - pm-enable config_split --uri=default --yes
    - config-import sync --uri=default --yes
    - features-import-all --uri=default --yes
    - cache-rebuild --uri=default --yes
