---
# Removing `-Dsync.files=true` as this is still requiring
# user input, even after testing with BLT Issue#1810.
- name: install site with BLT
  shell:
    cmd: vendor/bin/blt sync:refresh -y
    chdir: "{{ drupalvm_project_root }}"
