---
# I need to change this to sync:refresh once I update
# my BLT version
- name: install site with BLT
  shell:
    cmd: vendor/bin/blt sync:refresh -Dsync.files=true -y
    chdir: "{{ drupalvm_project_root }}"
