---
# Ansible role that uses BLT to refresh or install a site
# https://github.com/SU-SWS/drupal-caravan
# =======================================================
#
# The purpose of this role is to run a TASK, in this case an Acquia BLT
# process that downloads a fresh copy of the site's production database
# and files.
#
# INPUTS:
#   sitename
#   container_webserver_root
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# Acquia BLT in vendor directory.
#
# KNOWN ISSUES:
# - BLT seems to believe this is a "staging" site. The masthead should say "local".
#   Shea suggests: When you get the `staging` title that means that the config import failed,
#   but the db import succeeded. That could be indicative of an error in the config and not the process.
# - BLT still will not refresh the files directory without input, ie. -Dsync.files=true. To get around this,
#   I am first deleting the files directory, before running `sync:refresh`.

- name: install site with BLT
  shell:
    cmd: vendor/bin/blt sync:refresh -Dsync.files=true -y
    chdir: "{{ container_webserver_root }}{{ sitename }}"
