---
# Ansible role for setting up OSX to host a Docker container
# https://github.com/SU-SWS/drupal-caravan
# ==========================================================
#
# The purpose of this role is to run TASKS, that prepare a local, development
# machine to host a Docker container. We do not know what might be in someone's
# /etc/hosts file, for example. Nor would we ever want to overwrite their
# /etc/hosts file with a template that deletes all local entries.
#
# INPUTS:
#   sitename
#   container_ip_address
#   ansible_os_family
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# Permission to edit /etc/hosts
#
# KNOWN ISSUES:
# If someone is not able to restart the container on a Mac, check whether the
# ifconfig lo0 alias was actually created.
#

- name: Add container IP to /etc/hosts
  lineinfile:
    path: /etc/hosts
    insertafter: EOF
    line: "{{ container_ip_address }}  {{ item }}.local"
  become: true
  with_items:
    - "{{ sitename }}"
    - "behat.{{ sitename }}"

- name: Add IP alias
  template:
    src: caravan.docker.app.plist.j2
    dest: "{{ localhost_home_path }}/Library/LaunchAgents/caravan.docker.app.plist"
    owner: root
    group: wheel
    mode: 0644
  when: ansible_os_family == "Darwin"

- name: Load IP alias LaunchAgent
  command: "launchctl load {{ localhost_home_path}}/Library/LaunchAgents/caravan.docker.app.plist"
  become: true
