---
# Installed but needed to be linked, brew linkapps python3
- name: Install python3
  homebrew: name=python3 state=installed

- name: Set python3 as python alias
  lineinfile:
    path: ~/.bash_profile
    insertafter: EOF
    line: "alias python='python3'"

- name: Add container IP to /etc/hosts
  lineinfile:
    path: /etc/hosts
    insertafter: EOF
    line: "192.168.88.88  se3_blt.local"

- name: Add IP alias
  command: sudo ifconfig lo0 alias 192.168.88.88/24
  when: ansible_os_family == "Darwin"

- name: Restart apache
  command: brew services restart httpd22
