---
- name: Add container IP to /etc/hosts
  lineinfile:
    path: /etc/hosts
    insertafter: EOF
    line: "192.168.88.88  {{ sitename }}.local"
  notify: restart Apache
  become: true

- name: Add IP alias
  command: ifconfig lo0 alias 192.168.88.88/24
  become: true
  when: ansible_os_family == "Darwin"
  notify: restart Apache
