---
- name: Install pip
  pip: name={{ item }}
  sudo: true
  with_items:
   - docker-py
   - docker-compose

# Installed but needed to be linked, brew linkapps python3
- name: Install python3
  homebrew:
    name: python3
    state: present
    update_homebrew: yes

- name: Set python3 as python alias
  lineinfile:
    dest: "~/.bash_profile"
    insertafter: EOF
    line: "alias python='python3'"
    state: present

- name: source the updated ~/.bash_profile file
  command: source ~/.bash_profile

- name: Add container IP to /etc/hosts
  lineinfile:
    path: /etc/hosts
    insertafter: EOF
    line: "192.168.88.88  se3_blt.local"
  notify: restart Apache

- name: Add IP alias
  command: sudo ifconfig lo0 alias 192.168.88.88/24
  when: ansible_os_family == "Darwin"
  notify: restart Apache
