---
# Ansible role that positions custom configuration for DrupalVM
# https://github.com/SU-SWS/drupal-caravan
# =============================================================
#
# The purpose of this role is to instantiate a STATE, in this case the state of
# configuration files in the vendor/geerlingguy/drupal-vm directory.
#
# INPUTS:
#   sitename
#   container_webserver_root
#   container_site_install_directory
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# DrupalVM is installed in the vendor directory.
#
# KNOWN ISSUES:
# Editing any files in the surrounding build repository is less than ideal.
# In this case, I could find no other option for passing in custom variables
# to DrupalVM. Given that the DrupalVM playbooks are complete, ie. they are not
# just lists of tasks, they include hosts, etc. I can only be included in the
# setup-playbook unmodified.

- template:
    src: "config.yml.j2"
    dest: "{{ container_webserver_root }}{{ sitename }}/vendor/geerlingguy/drupal-vm/config.yml"
